
services:
  spotokn:
    image: ghcr.io/botxlab/spotokn:latest
    container_name: spotokn
    restart: unless-stopped
    ports:
      - "8080:8080"   # change if your app uses another port
    environment:
      PORT: 8080
      HEADLESS: true
      #BROWSER_PATH: /usr/bin/google-chrome
